/*******************************************************************************
 * Copyright (C) 2026 Commissariat a l'energie atomique et aux energies alternatives (CEA)
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * * Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 * * Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in the
 *   documentation and/or other materials provided with the distribution.
 * * Neither the name of CEA nor the names of its contributors may be used to
 *   endorse or promote products derived from this software without specific
 *   prior written permission.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 ******************************************************************************/

#include <array>
#include <vector> 
#include <iostream>
#include <string>
#include <type_traits>

#include <unistd.h>
#include <cstdlib>

#include <filesystem>
#include <iostream>
#include <numeric>
#include <ranges>

#include <pdi/testing.h>
#include "multiple_check_include.h"

template <typename T>
void check_type_value(const char *CONFIG_FILE, const std::string &name_var) {

	ASSERT_EQ(type_name<T>(), name_var) << "The type name is not corresponding to it string name";
	// reinitialize pdi for reading results
	PDI_init(PC_parse_string(CONFIG_FILE));
 	int size_pdi = -20;
	int damaris_nn = 0;
	static constexpr int const IMX = 10; // need to be static

	std::array<T, IMX> damaris_values;
	std::array<T, IMX> pdi_values;

	std::string pdi_var  = "pdi_" + name_var;
	std::string damaris_var = "damaris_" + name_var;

	ASSERT_TRUE(std::filesystem::exists("data_iter0.h5"));
	ASSERT_TRUE(std::filesystem::exists("./HDF5_files/damaris_scalar_type_It0.h5"));
	std::system("h5dump data_iter0.h5");
	std::system("h5dump ./HDF5_files/damaris_scalar_type_It0.h5");

	PDI_expose("pdi_nn", &size_pdi, PDI_INOUT);
	PDI_expose("damaris_nn", &damaris_nn, PDI_INOUT);

	ASSERT_EQ(IMX, size_pdi) << "For type "+name_var+", the size of the array must be size_pdi = "+std::to_string(IMX);
	ASSERT_EQ(IMX, damaris_nn) << "For type "+name_var+", the size of the array generated by damaris must be "+std::to_string(IMX);

	PDI_multi_expose(    "read_pdi",     pdi_var.c_str(),     pdi_values.data(), PDI_INOUT, NULL);
	PDI_multi_expose("read_damaris", damaris_var.c_str(), damaris_values.data(), PDI_INOUT, NULL);

	EXPECT_EQ( pdi_values, damaris_values);

	PDI_finalize();
}

void run_test(const std::string & my_type_name,const char *CONFIG_TO_CHANGE) {
	std::string my_new_config = replace_all(std::string(CONFIG_TO_CHANGE),std::string("MY8TYPE"), my_type_name);

	if (my_type_name == "short") {
		check_type_value<short>(my_new_config.c_str(), my_type_name);
	} else if ( my_type_name == "int") {
		check_type_value<int>(my_new_config.c_str(), my_type_name);
	} else if ( my_type_name=="long") {
		check_type_value<long>(my_new_config.c_str(), my_type_name);
	} else if ( my_type_name=="float") {
		check_type_value<float>(my_new_config.c_str(), my_type_name);
	} else if ( my_type_name=="double") {
		check_type_value<double>(my_new_config.c_str(), my_type_name);
	} else {
		throw std::runtime_error("This type is not supported");
	}
}

class DamarisCheckType: public ::PDI::PdiTestParam<std::string>
{};


TEST_P(DamarisCheckType, read)
{
	auto&& params = GetParam();
	//constexpr char * CONFIG_TO_CHANGE
	const char * CONFIG_TO_CHANGE
	= "logging: trace                                               \n"
	 "metadata:                                                     \n"
	"  pdi_nn: int                                                  \n"
	"  damaris_nn: int                                              \n"
	"data:                                                          \n"
	"  pdi_MY8TYPE: {size: ['$pdi_nn'], type: array, subtype: MY8TYPE}  \n"
	"  damaris_MY8TYPE: {size: ['$damaris_nn'], type: array, subtype: MY8TYPE}\n"
	"plugins:                                                       \n"
	"  trace: ~                                                     \n"
	"  decl_hdf5:                                                   \n"
	"    - file: './data_iter0.h5'                                  \n"
	"      read:                                                    \n"
	"        pdi_MY8TYPE:                                           \n"
	"          dataset: MY8TYPE_values                              \n"
    "        pdi_nn:                                                \n"
    "          size_of: MY8TYPE_values \n"
	"    - file: './HDF5_files/damaris_scalar_type_It0.h5'          \n"
	"      read:                                                    \n"
	"        damaris_MY8TYPE:                                       \n"
	"          dataset: MY8TYPE_values                              \n"
	"        damaris_nn:                                            \n"
    "          size_of: MY8TYPE_values \n";


	std::string exec_name = "test_write_check_multiple_type";
	std::string run_command = "mpirun -np 2 ../"+exec_name+" "+params;

    int result = std::system(run_command.c_str());
	ASSERT_EQ(result, 0);

	run_test(params, CONFIG_TO_CHANGE);	
}

std::vector<std::string> scalar_types{"short", "int", "long", "float", "double"};

INSTANTIATE_TEST_SUITE_P(, DamarisCheckType, testing::ValuesIn(scalar_types));